module.exports = {
  button1: {
    backgroundColor: "#ffffff",
    color: "#C6E0F7",
    fontSize: 35,
    fontWeight: "bold",
    padding: 10,
    borderRadius: 10,
    textAlign: "center",
    margin: 10,
    marginTop: 400,
  },
  button2: {
    backgroundColor: "#ffffff",
    color: "#C6E0F7",
    fontSize: 35,
    fontWeight: "bold",
    padding: 10,
    // padding: 10,
    borderRadius: 10,
    textAlign: "center",
    margin: 10,
    // marginTop: 400,
  },
  button3: {
    backgroundColor: "#4b66e4",
    color: "#ffffff",
    fontSize: 25,
    fontWeight: "bold",
    padding: 10,
    // padding: 10,
    borderRadius: 10,
    textAlign: "center",
    margin: 10,
    // marginTop: 400,
  },
};
